name: Terraform-apply

on:
  push:
    branches:
      - '!*'
      - 'master'

permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTIONS_RUNNER_DEBUG: false

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Run apply on terraform configuration
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create backend.tf
        working-directory: ${{ env.WORKING_DIR }}
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "s3" {
              bucket = "${{ secrets.TFSTATE_BUCKET }}"
              key    = "${{ secrets.TFSTATE_KEY }}"
              region = "${{ secrets.TFSTATE_REGION }}"
            }
          }
          EOF

      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        working-directory: ${{ env.WORKING_DIR }}
        id: init
        run: |
          terraform init --reconfigure

      - name: Terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: .
          variables: |
            aws_access_key = "${{ secrets.AWS_ACCESS_KEY }}"
            aws_secret_key = "${{ secrets.AWS_SECRET_KEY }}"
            sns_alert_email = "${{ secrets.SNS_ALERT_EMAIL }}"
            cw_alarm_period = "${{ secrets.CW_ALARM_PERIOD }}"
            cw_alarm_threshold = "${{ secrets.CW_ALARM_THRESHOLD }}"